import time
from selenium import webdriver
driver = webdriver.Chrome("C:\chromedriver.exe")
driver.maximize_window()
driver.get("https://practice.automationtesting.in/")
driver.execute_script("window.scrollBy(0, 900);")
a = driver.find_element_by_css_selector(".col3-1.first.sub_column :nth-child(2)")
a.click()
driver.execute_script("window.scrollBy(0, 500);")
b = driver.find_element_by_css_selector(".woocommerce-tabs :nth-child(2)")
b.click()
c = driver.find_element_by_css_selector(".stars :nth-child(5)")
c.click()
comment = driver.find_element_by_css_selector("#comment")
comment.send_keys("Nice book!")
name = driver.find_element_by_css_selector("#author")
name.send_keys("Artem")
mail = driver.find_element_by_css_selector("#email")
mail.send_keys("1@ya.ru")
time.sleep(3)
submit = driver.find_element_by_css_selector(".submit.submit")
submit.click()